###############################################################
# Variiables globales
replicas: 1
protocol: TCP
#strategy: Recreate # Cuando se actualialize del Deployment, los pods se eliminar치n antes de crear nuevos 
###############################################################
# Imagenes en repositorio Docker Hub
image:
  repo: bryyyan/practica_contendores
  webtag: appweb-k8s-v3 # Imagen para la applicaci칩n web
  dbtag: appdata-k8s-v2 # Imagen para la base de datos (PosgreSQL)
  adminer: adminer # Imagen para administrar la DDBB
  admitag: latest
  policy: IfNotPresent
###############################################################
# Web
# Variables para el deployment y servicio web
web:
  deploy:
    apiver: apps/v1
    name: web
    port: 5000 # Puerto interno del contenedor
  service:
    name: web-srv
    targetport: 80 # Puerto expuesto al que apunta el Ingress
  # Volumen donde se guardan los logs de la web
  # Se usa persistance volumen claim  
  volumen:
    name: web-claim0
    path: /app/logs
    storage: 50Mi # Minimo para iniciar
  resources:
    mincpu: 5m # Solicita un 5% al iniciar
  limits:
    maxcpu: 500m
    maxram: 500Mi
###############################################################
# Base de datos    
# Variables para el deployment y servicio DDBB
posgre:
  deploy:
    name: db
    port: 5432 # Puerto interno del contenedor
  service:
    name: db-srv
    targetport: 5432 # Puerto expuesto al que apunta el Ingress
  # Volumen donde se guardan los logs de la web  
  volumen:
    name: db-data
    path: /var/lib/postgresql/data
    storage: 100Mi # Minimo para iniciar   
###############################################################
# Adminer
# Variables para el deployment y servicio Adminer
adminer:
  deploy:
    name: adminer
    port: 8080 # Puerto interno del contenedor
  service:
    name: adminer-srv
    targetport: 50 # Puerto expuesto al que apunta el Ingress
###############################################################
# Secrets
# --set secret.cred.psquser=prueba1 --set secret.cred.psqpass=prueba1
secret: 
  cred:
    name: db-cred
    psqdb: test1        # POSTGRES_DB 
    psqhost: db         # DB_HOST
    psqport: "5432"     # DB_PORT 
    psqdbname: test1    # DB_NAME     
    psquser: ""         # DB_USER     
    psqpass: ""         # DB_PASS        
###############################################################
# Autoescalado
#Variables para desplehar el autoescalado horizontal para la ap침icaci칩n web
Load:
  name: app-hpa
  spec:
    maxrep: 5 # Numero maximo de replicas
    minrep: 2 # Numero minimo de replicas
  resource:
    # Se pide un 70% pero para probar lo pongo al 20
    avrcpu: 20 # Modificar el porcentaje de utilizacion de CPU
###############################################################
# Ingress
# Variableas para desplegar el acceso desde el exterior del cluster.
Ingress:
  name: web-igrss
  host: 192-168-49-2.nip.io # Se usa la IP de minikube tunel



    