# Valores de web
# Varaibles globales
replicas: 1
protocol: TCP
strategy: Recreate # Cuando se actualialize del Deployment, los pods se eliminarán antes de crear nuevos 

# Variables específicas
image:
  repo: bryyyan/practica_contendores
  webtag: appweb-k8s-v3
  dbtag: appdata-k8s-v2
  policy: IfNotPresent
  pullhub: docker-secret
# Variables para el deployment y servicio web
web:
  deploy:
    name: web
    port: 5000 # Puerto interno del contenedor
  service:
    name: web-srv
    tarjetport: 80 # Puerto expuesto al que apunta el Ingress
  # Volumen donde se guardan los logs de la web  
  volumen:
    name: web-claim0
    path: /app/logs
  resources:
    mincpu: 100m #100m # Solicita un 10% al iniciar
  limits:
    maxcpu: 1
    maxram: 500Mi
###############################################################
# Base de datos    
posgre:
  deploy:
    name: db
    port: 5432 # Puerto interno del contenedor
  service:
    name: db
    tarjetport: 5432 # Puerto expuesto al que apunta el Ingress
  # Volumen donde se guardan los logs de la web  
  volumen:
    name: db-data
    path: /var/lib/postgresql/data   




secret: 
  cred:
    name: db-cred
    psq-db: test1       # POSTGRES_DB=test1 
    psq-host: db        # DB_HOST=db
    psq-port: 5432      # DB_PORT=5432  
    psq-dbname: test1   # DB_NAME=test1     
    psq-user: prueba1   # DB_USER=prueba1     
    psq-pass: prueba1   # DB_PASS=prueba1     

  docker:
    user:
    pass:  

    