###############################################################
# Varaibles globales
replicas: 1
protocol: TCP
strategy: Recreate # Cuando se actualialize del Deployment, los pods se eliminarán antes de crear nuevos 
###############################################################
# Imagenes
# Variables específicas
image:
  repo: bryyyan/practica_contendores
  webtag: appweb-k8s-v3
  dbtag: appdata-k8s-v2
  adminer: adminer
  admitag: latest
  policy: IfNotPresent
  pullhub: docker-secret
###############################################################
# Web
# Variables para el deployment y servicio web
web:
  deploy:
    apiver: apps/v1
    name: web
    port: 5000 # Puerto interno del contenedor
  service:
    name: web-srv
    targetport: 80 # Puerto expuesto al que apunta el Ingress
  # Volumen donde se guardan los logs de la web
  # Se usa persistance volumen claim  
  volumen:
    name: web-claim0
    path: /app/logs
    storage: 50Mi # Minimo para iniciar
  resources:
    mincpu: 100m # Solicita un 10% al iniciar
  limits:
    maxcpu: 1
    maxram: 500Mi
###############################################################
# Base de datos    
posgre:
  deploy:
    name: db
    port: 5432 # Puerto interno del contenedor
  service:
    name: db-srv
    targetport: 5432 # Puerto expuesto al que apunta el Ingress
  # Volumen donde se guardan los logs de la web  
  volumen:
    name: db-data
    path: /var/lib/postgresql/data
    storage: 100Mi # Minimo para iniciar   
###############################################################
# Adminer
adminer:
  deploy:
    name: adminer
    port: 8080 # Puerto interno del contenedor
  service:
    name: adminer-srv
    targetport: 50 # Puerto expuesto al que apunta el Ingress
###############################################################
# Secrets
# --set secret.cred.psquser=prueba1 --set secret.cred.psqpass=prueba1
secret: 
  cred:
    name: db-cred
    psqdb: test1        # POSTGRES_DB 
    psqhost: db         # DB_HOST
    psqport: "5432"     # DB_PORT 
    psqdbname: test1    # DB_NAME     
    psquser: ""         # DB_USER     
    psqpass: ""         # DB_PASS       
  docker:
    name: docker-secret   
###############################################################
# Balanceador de carga
Load:
  name: app-hpa
  spec:
    maxrep: 5 # Numero maximo de replicas
    minrep: 2 # Numero minimo de replicas
  resource:
    avrcpu: 20 # Modificar el porcentaje de utilizacion de CPU
###############################################################
# Ingress
Ingress:
  name: web-igrss
  host: 192-168-49-2.nip.io # Se usa la IP de minikube tunel



    