# Valores de web
# Varaibles globales
replicas: 1
protocol: TCP

image:
  repo: bryyyan/practica_contendores
  webtag: appweb-k8s-v3
  dbtag: appdata-k8s-v2
  policy: IfNotPresent
  pullhub: docker-secret

# Variables específicas
web:
  deploy:
    name: web
    port: 5000 # Puerto interno del contenedor
  service:
    name: web-srv
    tarjetport: 80 # Puerto expuesto al que apunta el Ingress
  volumen:
    name: web-claim0
    path: /app/logs
  resources:
    mincpu: 100m
  limits:
    maxcpu: 1
    maxram: 500Mi
  Liveness:




secret: 
  cred:
    name: db-cred
    psq-db: test1       # POSTGRES_DB=test1 
    psq-host: db        # DB_HOST=db
    psq-port: 5432      # DB_PORT=5432  
    psq-dbname: test1   # DB_NAME=test1     
    psq-user: prueba1   # DB_USER=prueba1     
    psq-pass: prueba1   # DB_PASS=prueba1     

  docker:
    user:
    pass:  

    