###############################################################
# Varaibles globales
replicas: 1
protocol: TCP
strategy: Recreate # Cuando se actualialize del Deployment, los pods se eliminarán antes de crear nuevos 
###############################################################
# Imagenes
# Variables específicas
image:
  repo: bryyyan/practica_contendores
  webtag: appweb-k8s-v3
  dbtag: appdata-k8s-v2
  adminer: adminer
  admitag: latest
  policy: IfNotPresent
  pullhub: docker-secret
###############################################################
# Web
# Variables para el deployment y servicio web
web:
  deploy:
    name: web
    port: 5000 # Puerto interno del contenedor
  service:
    name: web-srv
    tarjetport: 80 # Puerto expuesto al que apunta el Ingress
  # Volumen donde se guardan los logs de la web  
  volumen:
    name: web-claim0
    path: /app/logs
  resources:
    mincpu: 100m #100m # Solicita un 10% al iniciar
  limits:
    maxcpu: 1
    maxram: 500Mi
###############################################################
# Base de datos    
posgre:
  deploy:
    name: db
    port: 5432 # Puerto interno del contenedor
  service:
    name: db
    tarjetport: 5432 # Puerto expuesto al que apunta el Ingress
  # Volumen donde se guardan los logs de la web  
  volumen:
    name: db-data
    path: /var/lib/postgresql/data   
###############################################################
# Adminer
adminer:
  deploy:
    name: adminer
    port: 8080 # Puerto interno del contenedor
  service:
    name: adminer-srv
    tarjetport: 50 # Puerto expuesto al que apunta el Ingress
###############################################################
# Secrets
secret: 
  cred:
    name: db-cred
    psqdb: test1       # POSTGRES_DB=test1 
    psqhost: db        # DB_HOST=db
    psqport: 5432      # DB_PORT=5432  
    psqdbname: test1   # DB_NAME=test1     
    psquser: prueba1   # DB_USER=prueba1     
    psqpass: prueba1   # DB_PASS=prueba1     
  docker:
    name: docker-secret   

    