apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.adminer.deploy.name }}"
  labels:
    app: {{ .Values.adminer.deploy.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.adminer.deploy.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.adminer.deploy.name }}
    spec:
      containers:
        - image: "{{ .Values.image.adminer }}:{{ .Values.image.admitag }}"
          name: "{{ .Release.Name }}-{{ .Values.adminer.service.name }}"
          ports:
            - containerPort: {{ .Values.adminer.deploy.port }}
              protocol: {{ .Values.protocol }}
      restartPolicy: Always

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.adminer.service.name }}"
  labels:
    app: {{ .Values.adminer.deploy.name }}
spec:
  ports:
    - protocol: {{ .Values.protocol }}
      port: {{ .Values.adminer.service.targetport }} # 80
      targetPort: {{ .Values.adminer.deploy.port }} # 8080
  selector:
    app: {{ .Values.adminer.deploy.name }}