apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.k8s.io: {{ .Values.posgre.deploy.name }}
  name: {{ .Values.posgre.deploy.name }}
spec:
  serviceName: {{ .Values.posgre.service.name }}  # Añadido
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.k8s.io: {{ .Values.posgre.deploy.name }}
  template:
    metadata:
      labels:
        app.k8s.io: {{ .Values.posgre.deploy.name }}
    spec:
      containers:
      - name: {{ .Values.posgre.service.name }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.dbtag }}"
        ports:
        - containerPort: {{ .Values.posgre.deploy.port }}
          protocol: {{ .Values.protocol }}
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                key: psqhost
                name: db-cred
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: psqdbname
                name: db-cred
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: psqpass
                name: db-cred
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                key: psqport
                name: db-cred
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: psquser
                name: db-cred
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                key: psqdb
                name: db-cred
        volumeMounts:
        - mountPath: {{ .Values.posgre.volumen.path }}
          name: postgres-storage  # Volumen persistente para cada pod
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-secret
  volumeClaimTemplates:          # Añadido
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.posgre.volumen.storage }}  # Tamaño del almacenamiento solicitado
