apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.k8s.io: {{ .Values.posgre.volumen.name }}
  name: {{ .Values.posgre.volumen.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.posgre.volumen.storage }}