apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.cred.name }}
type: Opaque
data:
  psqdb: {{ .Values.secret.db.psqdb | b64enc }}
  psqhost: {{ .Values.secret.db.psqhost | b64enc }}
  psqport: {{ .Values.secret.db.psqport | b64enc }}
  psqdbname: {{ .Values.secret.db.psqdbname | b64enc }}
  psquser: {{ .Values.secret.db.psquser | b64enc }}
  psqpass: {{ .Values.secret.db.psqpass | b64enc }}