apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-{{ .Values.posgre.deploy.name }}"
  labels:
    app: {{ .Values.posgre.deploy.name }}
spec:
  serviceName: "{{ .Release.Name }}-{{ .Values.posgre.service.name }}"
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.posgre.deploy.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.posgre.deploy.name }}
    spec:
      containers:
      - name: {{ .Values.posgre.deploy.name }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.dbtag }}"
        ports:
        - containerPort: {{ .Values.posgre.deploy.port }}
          protocol: {{ .Values.protocol }}
        env:
          - name: DB_HOST
            value: "{{ .Release.Name }}-{{ .Values.posgre.service.name }}" # Nuevo cambio
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: psqdbname
                name: db-cred
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: psqpass
                name: db-cred
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                key: psqport
                name: db-cred
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: psquser
                name: db-cred
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                key: psqdb
                name: db-cred
        volumeMounts:
        - mountPath: {{ .Values.posgre.volumen.path }}
          name: {{ .Values.posgre.volumen.name }}  # Volumen persistente para cada pod
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-secret
  #  crea PVCs únicos para cada réplica del StatefulSet, garantizando que cada pod tenga su propio volumen persistente
  volumeClaimTemplates:          
  - metadata:
      name: {{ .Values.posgre.volumen.name }}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.posgre.volumen.storage }}  # Tamaño del almacenamiento solicitado

# Service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.posgre.deploy.name }}
  name: "{{ .Release.Name }}-{{ .Values.posgre.service.name }}"
spec:
  clusterIP: None #Headless service
  ports:
    - protocol: {{ .Values.protocol }}
      port: {{ .Values.posgre.service.targetport }}
      targetPort: {{ .Values.posgre.service.targetport }}
  selector:
    app: {{ .Values.posgre.deploy.name }}