apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.cred.name }}
type: Opaque
data:
    psqdb: {{ ENC[AES256_GCM,data:sy+SgR8=,iv:Z8RTTSq0/dLri1cJ9d3G+66O5VEhkRQ8NFESQvVAj08=,tag:LwBlS89yufYuq41TRQPAvg==,type:str] | b64enc }}
    psqhost: {{ ENC[AES256_GCM,data:ni0=,iv:3JXRlab5gTNPTLE9gLW90i29LLhCAhnJd/g0XNgmBhs=,tag:6p19xBgqOhCOIHt0o6/MsA==,type:str] | b64enc }}
    psqport: {{ ENC[AES256_GCM,data:I2eixQ==,iv:TIMMoYMAeK9SzfkCQ2Leo7AtElLtrzpcYINANRunLnA=,tag:xoAgd3Ne9mfGsgI07uhBBg==,type:str] | b64enc }}
    psqdbname: {{ ENC[AES256_GCM,data:LfR2B+g=,iv:n67K5W9xFSu5wjWn/yhqPOEhjE7ttC9xACDJeiyJQGc=,tag:Q312Lwo5xBNv58hYBBn87A==,type:str] | b64enc }}
    psquser: {{ ENC[AES256_GCM,data:EkneZdEOng==,iv:WhdgmLexuNKxvtOH6QCj02pkSDNzJN9Ey/9AWJ46C1c=,tag:coO6KeaHKprPtCHwFT71Eg==,type:str] | b64enc }}
    psqpass: {{ ENC[AES256_GCM,data:hae3n1j0Jw==,iv:WtOiaPLxfzuPTNPCXUMNkDUNxV6gwdm66ThEGLE+7Rc=,tag:sekXhgoMAjwSPDtS4qauOQ==,type:str] | b64enc }}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-26T21:13:32Z"
    mac: ENC[AES256_GCM,data:whnPsmOkH5Mc/xIQ/RbwpplTdYUu3kQCzpkO+Vf7XpU4Ij6Oj35a5qyo4HPbxeGJT+KQKSvVmnczIQJhp3p247AiFrRdwQ26sct0mn6Y/g+DOBR1Sm+mB4FJHbukMZE8wNWGHL2HXcWRH1oY+n+MQDWGCmBiuoxK8NeIofQ1EYs=,iv:CgQv6ukmyNCkpXhFtCGnCPEKyjjAoGpFNWSx5MLJ2Y0=,tag:maPOxyayKGTNLVWHIigrEg==,type:str]
    pgp:
        - created_at: "2024-09-26T21:13:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6BvOFTlmtOrAQ/+N6pLq6zD5II/qRJq/yaH/RD//QDVQLzPjVFHGuZUbdZE
            XVV81erICsehUClKLqAisWE+bC9vUfEJtldn0XUJakIoVeQ4sYw1dcUs8r4f7eQ1
            0Aa30K9xHEEJWiMe/k1MyZe1Al7Ajd9t37MmNa9n/+fWjJ9YpRTZnYMkTvV68v34
            HZ+waGDCAskqM419OIecuU4EuJe2DuE5Qb7v+SaQfN+Tz4TQHahfL7ZshhMMNP8k
            3MZrTYFbythas2Omq5VKIkZ1NWBNBdlUBKNz5yWWcpyity4X17qNQ4Mj5x0Gzz/e
            md5+pdsdYxwKwNeqJEHevCXdT86GCuawGQfnLs6n/S3f+7rwcSQV6nnA3dHlIMud
            FtPiUZDSc4MElLV4wC6GdSviMv7BWivRgv/iXczGS7V23Pk2T6oHlJKiF8WGO5yK
            GVi6oV3l6Ll3t6GY+9Iwghk6lFgfVxq/QwZ23bzB6GGpe2nilwXQxBhUPDRjl/Ad
            yL45fbsZljPACsuxFBw/wgJA2Jb8BqnBaKKZ77OusV6Htz84m96q85Fsf74ObXka
            PNre8XspnwA1oM2x+27yQRrxOcJQOHhzenBUy1DbQTep35Z6F6k57GjDrS9HJ+sb
            5pZE1UFYRJzKpo/DwC1BY5D3Cgo2vZE27YvCJjfPpJPaLHXsYcKxVeoJTkGreg7U
            ZgEJAhDWWdK7tSoQfnEphl4sP+qp3wi+tYynYSfoiLKb3jeK87CnNcc3PE0oDdst
            nXhbPMacRK3vMhc/Ak1ArU6MgNrHWZTJHlrSgZmfiGeoU+SsrW39VUurTbhTO/1t
            HhMfFMzGuA==
            =7Vb+
            -----END PGP MESSAGE-----
          fp: 06A3D1814F4861A5
    unencrypted_suffix: _unencrypted
    version: 3.9.0