apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.cred.name }}
type: Opaque
data:
  psq-db: {{ .Values.secret.db.psq-db | b64enc }}
  psq-host: {{ .Values.secret.db.psq-host | b64enc }}
  psq-port: {{ .Values.secret.db.psq-port | b64enc }}
  psq-dbname: {{ .Values.secret.db.psq-dbname | b64enc }}
  psq-user: {{ .Values.secret.db.psq-user | b64enc }}
  psq-pass: {{ .Values.secret.db.psq-pass | b64enc }}