apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.cred.name }}
type: Opaque
data:
  psqdb: {{ .Values.secret.cred.psqdb | b64enc }}
  psqhost: {{ .Values.secret.cred.psqhost | b64enc }}
  psqport: {{ .Values.secret.cred.psqport | b64enc }}
  psqdbname: {{ .Values.secret.cred.psqdbname | b64enc }}
  psquser: {{ .Values.secret.cred.psquser | b64enc }}
  psqpass: {{ .Values.secret.cred.psqpass | b64enc }}