apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.cred.name }}
type: Opaque
data:
  psqdb: {{ .Values.secret.cred.psqdb }}
  psqhost: {{ .Values.secret.cred.psqhost }}
  psqport: {{ .Values.secret.cred.psqport }}
  psqdbname: {{ .Values.secret.cred.psqdbname }}
  psquser: {{ .Values.secret.cred.psquser }}
  psqpass: {{ .Values.secret.cred.psqpass }}