apiVersion: v1
kind: Service
metadata:
  labels:
    app.k8s.io: {{ .Values.web.deploy.name }}
  name: {{ .Values.web.service.name }}
spec:
  type: ClusterIP
  ports:
    - protocol: {{ .Values.protocol }}
      port: {{ .Values.web.service.targetport }} # Puerto expuesto al que apunta el Ingress
      targetPort: {{ .Values.web.deploy.port }} # Puerto interno del contenedor
  selector:
    app.k8s.io: {{ .Values.web.deploy.name }}
