apiVersion: apps/v1
kind: Deployment
metadata:   
  name: "{{ .Release.Name }}-web-deployment"
  labels: 
    app.k8s.io: "{{ .Release.Name }}-web"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.k8s.io: "{{ .Release.Name }}-web"
  strategy:
    type: Recreate # Poner en variable 
  template:
    metadata:
      labels:
        app.k8s.io: "{{ .Release.Name }}-web"
    spec:
      containers:
      - name:  # Nombre del servicio
        image: "{{ .Values.web.imagen.repo }}:{{ .Values.web.imagen.tag }}"
        ports: 
          - containerPort: "{{ .Values.web.port }}"
            protocol: "{{ .Values.protocol }}"
        # Comando que espera a los la DDBB este lista    
        command:
          - sh
          - -c
          - sleep 10 && python app.py
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: DB_HOST
                name: {{  }}




