apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.Load.name }}
spec:
  maxReplicas: {{ .Values.Load.spec.maxrep }} #numero maximo de replicas
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.Load.resource.avrcpu }} # Modificar el porcentaje de utilizacion de CPU
        type: Utilization
    type: Resource
  minReplicas: {{ .Values.Load.spec.minrep }}
  # Apunta al deployment de la web
  scaleTargetRef:
    apiVersion: {{ .Values.web.deploy.apiver }} #apps/v1
    kind: Deployment
    name: "{{ .Release.Name }}-{{ .Values.web.deploy.name }}" 