apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-keepcoding
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-keepcoding
  livenessProbe:
    httpGet:
    path: /
    port: 80
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:    
    httpGet:
    path: /
    port: 80
    initialDelaySeconds: 5
    periodSeconds: 10      
  template:
    metadata:
      labels:
        app: app-keepcoding
    spec:
      containers:
      - name: contenedor-keepcoding
        image: nginx:latest
        ports:
        - containerPort: 80