apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  labels:
    io.app.service: adminer
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.app.service: adminer


