apiVersion: v1
kind: Service
metadata:
  labels:
    app.k8s.io: adminer
  name: adminer
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app.k8s.io: adminer

