apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  #labels:
  #  app.k8s.io: web
  name: web-igrss
  namespace: default
spec:
  rules:
  - host: 192-168-49-2.nip.io #localhost #web-127-0-0-1.nip.io
    http:
      paths:
      - path: /notes
        pathType: Prefix
        backend:
          service:
            name: web-srv
            port:
              number: 80

