apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  type: ClusterIP
  ports:
    # - name: "5000"
    - port: 5000 # Puerto del contenedor escucha
      targetPort: 5000 # Puerto interno del contenedor
  selector:
    io.kompose.service: web