# Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      app: db
  # Cuando se actualialize del Deployment, los pods se eliminarán antes de crear nuevos    
  #strategy:
    #type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: bryyyan/practica_contendores:appdata-k8s-v2
        ports:
        - containerPort: 5432
          protocol: TCP
        # Variables de entorno para configura la base de datos  
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: db-cred
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: env-test1-env
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: DB_PASS
              name: db-cred # Uso de secret para variables sensibles
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: env-test1-env
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: env-test1-env
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: db-cred
        # Montar un volumen persistente      
        volumeMounts:
        - name: data 
          mountPath: /var/lib/postgresql/data
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi

# Service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: db